### ISSUE TITLE
[Bug]: 加载自定义 output view 时需要考虑 mountpoint ? 

### ISSUE THREAD

**Issue by donotlb** [AIGNE-io/aigne-studio#1199]
### Describe the bug

discuss kit dev 环境的 mountpoint 是 /discuss, 生成的 component.yml 如下: 

```yml
title: Discuss Kit Actions
description: Discuss Kit Actions
version: 1.0.0
type: react-component-protocol
blocklet:
  name: did-comments
  title: Discuss Kit
  did: z8ia1WEiBZ7hxURf6LwH21Wpg99vophFwSJdu
components:
  - name: Actions Output View
    url: /output-view.es.mjs?1719910577983
    tags:
      - aigne-view
```

配置组件后, agent preview 时加载报错, 感觉路径少了 mountpoint 

![image](https://github.com/blocklet/ai-studio/assets/24994263/934e134e-9561-466a-b8e2-d612cd1c9ff2)
